# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import gkey

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Load csv

weather_data = pd.read_csv("../WeatherPy/Output_Data/cities.csv")
weather_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Pevek,69.7008,170.3133,-2.72,97,100,12.93,RU,1615732397
1,Saskylakh,71.9167,114.0833,-28.86,86,74,4.45,RU,1615732397
2,Isla Vista,34.4133,-119.8610,50.00,87,90,5.75,US,1615732398
3,Saint-François,46.4154,3.9054,50.00,53,75,17.27,FR,1615732398
4,Hilo,19.7297,-155.0900,69.80,83,90,4.61,US,1615732160
...,...,...,...,...,...,...,...,...,...
551,Pine Bluff,34.2284,-92.0032,60.80,88,90,8.05,US,1615732501
552,Jumla,29.2747,82.1838,44.87,79,4,4.14,NP,1615732561
553,Norwich,52.6278,1.2983,53.01,58,40,18.41,GB,1615732561
554,Guanare,9.0418,-69.7421,80.60,65,81,3.44,VE,1615732561
555,Renfrew,55.8720,-4.3925,46.00,87,90,13.80,GB,1615732532

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure